// <auto-generated />
namespace SuperHeroes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Super_Heroes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Super_Heroes));
        
        string IMigrationMetadata.Id
        {
            get { return "201903051310348_Super_Heroes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
